FROM ubuntu:24.04

ARG project_dir=/home/ubuntu/project
ARG ruby_version=3.1.4
ARG node_version=24.15.0
ARG nvm_version=0.40.4

RUN \
apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
build-essential \
ca-certificates \
curl \
git \
make \
openssh-client \
sudo \
wine-stable \
zip \
zlib1g-dev

# Workaround for electron packager
RUN \
echo -e '#!/bin/bash\nwine "$@"' > /usr/bin/wine64 && \
chmod +x /usr/bin/wine64

# Disable password prompt for sudo commands
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Run everything below as $user
USER ubuntu
WORKDIR ${project_dir}

RUN \
cd && \
git clone https://github.com/nvm-sh/nvm && \
cd nvm && \
git checkout v${nvm_version} && \
./install.sh && \
cd .. && \
rm -rf nvm

RUN \
curl -sSL https://get.rvm.io | bash -s stable && \
/home/ubuntu/.rvm/bin/rvm install ${ruby_version}

ENV RUBY_VERSION=${ruby_version}
ENV NODE_VERSION=${node_version}
ENV NVM_DIR=/home/ubuntu/.nvm
ENV PATH=/home/ubuntu/.rvm/rubies/ruby-${ruby_version}/bin:/home/ubuntu/.nvm/versions/node/v${node_version}/bin:${PATH}

RUN \
gem install \
jekyll

RUN \
[ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh" && \
nvm install ${node_version} && \
npm install -g electron-packager gulp-cli yarn

ADD .devcontainer/.git_branch_bash /home/ubuntu/.git_branch_bash

RUN \
tee -a /home/ubuntu/.bashrc <<EOF
[ -s /home/ubuntu/.nvm/nvm.sh ] && source /home/ubuntu/.nvm/nvm.sh
alias mkc='make clean'
source /home/ubuntu/.git_branch_bash
source /usr/share/bash-completion/completions/git
EOF
